BEGIN;

UPDATE "users"
SET "role" = 'ADMINISTRATOR'
WHERE "role" = 'SYSTEM_ADMINISTRATOR';

ALTER TYPE "Role" RENAME TO "Role_old";

CREATE TYPE "Role" AS ENUM ('ADMINISTRATOR', 'STAFF');

ALTER TABLE "users"
ALTER COLUMN "role" TYPE "Role"
USING ("role"::text::"Role");

DROP TYPE "Role_old";

COMMIT;
